#!/bin/sh
# Put Homebrew's GTK stack on the pkg-config search path, and fill in the
# pkg-config files Homebrew's xorgproto keg does not ship. Source it; running
# it does nothing useful.
#
#   . build-aux/homebrew-env.sh
#   cargo build --release

brew_prefix=$(brew --prefix 2>/dev/null) || {
    echo "homebrew-env.sh: Homebrew is not installed" >&2
    return 1 2>/dev/null || exit 1
}

here=$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]:-$0}")" && pwd)
shims="$here/pkgconfig"
xorgproto="$brew_prefix/opt/xorgproto"

# Brew's x11.pc, xext.pc and xrender.pc list these under Requires:, so every
# pkg-config query that reaches Cairo — which is every gtk4-sys build — fails
# without them. They are header-only, so a Cflags line is the whole file.
if [ -d "$xorgproto/include" ]; then
    mkdir -p "$shims"
    for proto in \
        xproto:7.0.31 kbproto:1.0.7 xextproto:7.3.0 renderproto:0.11.1 \
        inputproto:2.3.2 fixesproto:5.0 damageproto:1.2.1 compositeproto:0.4.2 \
        randrproto:1.5.0 scrnsaverproto:1.2.2 xineramaproto:1.2.1 \
        presentproto:1.2 dri3proto:1.2 xf86vidmodeproto:2.3.1
    do
        name=${proto%%:*}
        version=${proto##*:}
        cat > "$shims/$name.pc" <<PC
# Generated by build-aux/homebrew-env.sh. Do not edit; do not commit.
prefix=$xorgproto
includedir=\${prefix}/include

Name: $name
Description: X11 protocol headers (Homebrew xorgproto shim)
Version: $version
Cflags: -I\${includedir}
PC
    done
else
    echo "homebrew-env.sh: xorgproto is not installed; run 'brew install xorgproto'" >&2
fi

PKG_CONFIG_PATH="$shims:$brew_prefix/lib/pkgconfig:$brew_prefix/share/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
export PKG_CONFIG_PATH

echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH"
